### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb8 in position 27: invalid start byte

### ISSUE THREAD

**Issue by ilya-fedin** [rsalmei/zsh-history-to-fish#2]
```
Traceback (most recent call last):
  File "/home/ilya/zsh-history-to-fish/virtualenv/bin/zsh-history-to-fish", line 10, in <module>
    sys.exit(exporter())
  File "/home/ilya/zsh-history-to-fish/virtualenv/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ilya/zsh-history-to-fish/virtualenv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ilya/zsh-history-to-fish/virtualenv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ilya/zsh-history-to-fish/virtualenv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ilya/zsh-history-to-fish/virtualenv/lib/python3.7/site-packages/zsh_history_to_fish/command.py", line 68, in exporter
    for line in history(input):
  File "/home/ilya/zsh-history-to-fish/virtualenv/lib/python3.7/site-packages/zsh_history_to_fish/command.py", line 17, in history
    line = line.replace(b'\xe2\x80\x83\xb4', b'-').decode('utf-8').strip()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb8 in position 27: invalid start byte
```

**Comment by guihkx** [comment]
Here's a workaround. Edit the following line in `command.py`:

https://github.com/rsalmei/zsh-history-to-fish/blob/b807eb1842c31d08d30972a2165c0f1e6dcbc7ea/zsh_history_to_fish/command.py#L17

And replace this part:

```python
decode('utf-8')
```

By this:

```python
decode('utf-8', errors='ignore')
```

Save the file and run the script again.

**Comment by timokau** [comment]
The source of this problem is that zsh's history file is [not actually unicode](https://www.zsh.org/mla/workers/2016/msg02057.html). I have [worked around this](https://github.com/xonsh/xonsh/issues/1614#issuecomment-483386184) before by using zsh itself to parse the history to unicode. The workaround could be adapted for this library.

**Comment by rsalmei** [comment]
Hello! Sorry for the delay, haven't seen this message before.

Humm, that's a shame zsh do not use utf-8... I was planning to make the inverse tool too, converting fish history to zsh, but that ruins it.

Anyway, I can try to use zsh itself to import it, like you suggested, thank you!

**Comment by rsalmei** [comment]
Hey @timokau, very nice trick you did there! Can't say I actually understood it, using two `fc` in the same line, with `-R` in the first, and `-t` in second 😂! But it does work!

I implemented it last night in my tool, going to release it today!

Thanks.

**Comment by rsalmei** [comment]
Here it is: https://github.com/rsalmei/zsh-history-to-fish/pull/3

**Comment by rsalmei** [comment]
Hey @ilya-fedin, I've released the new version, using @timokau's trick!
Please confirm if that does work now, ok?

**Comment by ilya-fedin** [comment]
Oh, I don't have zsh history, because I completely switched to fish a long time ago :smile: 
But I think the issue can be closed and if someone encounter in this issue later, he will just open a new one :)

**Comment by rsalmei** [comment]
Yeah, I see.

I'd just like to confirm with @timokau if it would be possible to generate zsh history, as to bring fish history to zsh...

**Comment by timokau** [comment]
> Hey @timokau, very nice trick you did there! Can't say I actually understood it, using two `fc` in the same line, with `-R` in the first, and `-t` in second joy! But it does work!

It's been a while and I don't really remember why I did it that way either. But it looks like the first `fc` forces zsh to read the whole history while the second `fc` prints it (in unicode).

> I've implemented it last night in my tool, going to release it today!

Great!

**Comment by timokau** [comment]
> I'd just like to confirm with @timokau if it would be possible to generate zsh history, as to bring fish history to zsh...

I haven't done that yet. Probably possible with this `print -s` approach: https://stackoverflow.com/questions/2816225/how-can-i-from-a-script-add-something-to-the-zsh-command-history

Note that `man zshbuiltins` will also give you the documentation for `fc`, which should explain the command I used for exporting.

**Comment by rsalmei** [comment]
Yeah thanks, I'd found that same stackoverflow question...
I think `print -s` would not be _that_ adequate since I couldn't bring the original timestamp too. But the commands would possibly work.

Also I read the `fc` in that man page, but couldn't quite understand anyway 😬 
Thanks man.

**Comment by GoingMyWay** [comment]
It is still a problem. Following this [link](https://gist.github.com/dvdbng/e08ce5ba50f224b59c9fe2a91fdcea61#file-zsh_to_fish-py) can solve the issue.

**Comment by rsalmei** [comment]
Which link @GoingMyWay?
Which Python are you using?

**Comment by GoingMyWay** [comment]
> Which link @GoingMyWay? Which Python are you using?

Hi @rsalmei, it is Python 3.7 on macOS Intel

**Comment by rsalmei** [comment]
Humm, the Python is recent enough, and the macOS platform shouldn't matter.
What link are you referring to?

**Comment by GoingMyWay** [comment]
> Humm, the Python is recent enough, and the macOS platform shouldn't matter. What link are you referring to?

Hi, here is the link: https://gist.github.com/dvdbng/e08ce5ba50f224b59c9fe2a91fdcea61#file-zsh_to_fish-py
