### ISSUE TITLE
History entries not showing in fish

### ISSUE THREAD

**Issue by perkfly** [rsalmei/zsh-history-to-fish#6]
```
┬─[yifei@bogon:~]─[14:10:51]
╰─>$ zsh-history-to-fish -n
ZSH history to Fish
===================
input : /Users/yifei/.zsh_history (naive-convert=False)
output: /Users/yifei/.local/share/fish/fish_history
.
Processed 1000 commands.

File "/Users/yifei/.local/share/fish/fish_history" has been written successfully.
┬─[yifei@bogon:~]─[14:11:08]
╰─>$ history | wc -l
     289
```

I can see the commands are already in `~/.local/share/fish/fish_history`, but fish seems to ignore them.

**Comment by perkfly** [comment]
It seems that fish does not incorporate all the history entries at once, the imported items shows up after an hour or so. However, I guess the doc could be updated to tell users that there might be a latency.

**Comment by markus-meissner** [comment]
FYI: The entries show up after the history has been "vacuumed". That happens at least every 25 commands entered, see `countdown_to_vacuum` in `history.cpp`.
